name: Publish Package
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install
      - run: npm run release